version: '3'

services:
  schedule-backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      schedule-db:
        condition: service_healthy
    restart: always

  schedule-db:
    image: postgres:latest
    container_name: schedule-db
    volumes:
      - schedule_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # telegram-bot:
  #   build:
  #     context: ./telegram_bot
  #   volumes:
  #     - ./telegram_bot:/app
  #   env_file:
  #     - .env
  #   restart: always

volumes:
  schedule_data:
